Update README
contentful-labs/ui-editable-table pull request #1
Opened 2018-05-31 08:39 UTC by KikahaPlus44

2018-05-31 09:03 UTC, stefanjudis requested changes
@KikahaPlus44 👋🏻

Thanks so much for opening this PR. Copy and paste is evil. :)

As you cleaned up paths I have a tiny additional change request. :)

2018-05-31 09:03 UTC, stefanjudis commented on README.md
> +Licensed under the [MIT license](https://github.com/contentful/developer-relations/ui-country-select/blob/master/LICENSE).
Can you update this path, too? 😊

2018-06-01 12:57 UTC, KikahaPlus44 commented on README.md
> +Licensed under the [MIT license](https://github.com/contentful/developer-relations/ui-country-select/blob/master/LICENSE).
:) why not

2018-06-03 19:00 UTC, merged

2018-06-03 19:00 UTC, stefanjudis commented
Thanks so much. 👍